In [46]:
import numpy as np
%load_ext iminizinc

The iminizinc extension is already loaded. To reload it, use:
  %reload_ext iminizinc


#### Defining Priority Values

The priority values used in this model are:
- 'Low'
- 'Medium'
- 'High'
- 'Very High'
- 'Emergency'

In [47]:
PriorityDict = {'Low':5,'Medium':10,'High':15,'Very High':20,'Emergency':25}

#### Defining Paths

The path values used in this model are:
- 'NW' (North to West)
- 'NS' (North to South)
- 'NE' (North to East)
- 'WS' (West to South)
- 'WE' (West to East)
- 'WN' (West to North)
- 'SE' (South to East)
- 'SN' (South to North)
- 'SW' (South to West)
- 'EN' (East to North)
- 'EW' (East to West)
- 'ES' (East to South)

In [48]:
PathDict = {'SN':1,'SE':2,'EW':3,'EN':4,'NS':5,'NW':6,'WE':7,'WS':8,'SW':9,'ES':10,'NE':11,'WN':12}

#### Empty Intersection Generation

In [49]:
def GenEmptyIntersection():
    Path = np.zeros((12,),dtype=int)
    Queue = np.zeros((12,2,15))
    return Path.tolist(), Queue.tolist()

In [50]:
# oldPaths, WaitingQueue = GenEmptyIntersection()

#### Random Intersection Generation

In [51]:
def GenRandomIntersection():
    Path = np.zeros((12,),dtype=int)
    Queue = np.random.randint(5,size=(12,2,15))
    Queue = Queue * 5
    Queue = Queue + 5
    for i in range(0,12):
        for j in range(0,15):
            Queue[i,1,j] = 0
    return Path.tolist(), Queue.tolist()

In [52]:
oldPaths, WaitingQueue = GenRandomIntersection()
print(oldPaths)
print(WaitingQueue)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[[[20, 15, 5, 15, 15, 15, 15, 5, 5, 25, 20, 20, 10, 5, 25], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], [[5, 5, 15, 5, 5, 15, 15, 5, 25, 25, 10, 10, 5, 25, 10], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], [[15, 5, 5, 15, 10, 25, 25, 20, 5, 15, 20, 10, 20, 10, 15], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], [[25, 20, 10, 15, 15, 20, 20, 20, 5, 10, 20, 25, 20, 25, 20], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], [[20, 5, 20, 25, 10, 5, 20, 25, 25, 10, 15, 15, 15, 15, 20], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], [[25, 5, 5, 5, 15, 25, 20, 25, 20, 10, 15, 5, 20, 25, 15], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], [[20, 15, 15, 15, 5, 25, 20, 5, 10, 20, 20, 20, 25, 10, 20], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], [[25, 10, 15, 5, 15, 10, 10, 10, 10, 5, 10, 5, 5, 25, 15], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], [[15, 15, 10, 10, 20, 10, 20, 25, 25, 15, 10, 20, 5, 10, 15], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

#### Add Vehicle to the existing Queue at a specific lane

In [53]:
def AddVehicle(Priority, Path, Queue):
    Wait = np.array(Queue)
    assert Priority in PriorityDict,"Not a valid Priority"
    assert Path in PathDict,"Not a valid Path"
    
    for j in range(0,15):
        if Wait[PathDict[Path]-1,0,j] == 0:
            Wait[PathDict[Path]-1,0,j]=PriorityDict[Priority]
            break
    return Wait.tolist()            

In [54]:
# WaitingQueue = AddVehicle('Low','SE',WaitingQueue)
# print(np.array(WaitingQueue))

#### Manually generated Queue for Intersection

In [55]:
# WaitingQueue= [[[ 1, 5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],[61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 0, 0 ]],
# [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],[61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61]],
# [[1, 1, 1, 1, 1, 2, 1, 3, 1, 1, 1, 1, 1, 1, 1 ],[61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61]],
# [[1, 6, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],[61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 0, 0]],
# [[4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],[61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 0, 0]],
# [[1, 1, 1, 1, 6, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],[61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 0, 0]],
# [[1, 1, 1, 1, 1, 1, 1, 1, 1, 5, 1, 1, 1, 0, 0],[61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 0, 0]],
# [[1, 1, 1, 7, 1, 1, 1, 4, 1, 1, 1, 1, 1, 0, 0],[61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 0, 0]],
# [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],[61, 61, 61, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 0]],
# [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],[61, 61, 61, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 0]],
# [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],[61, 61, 61, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 0]],
# [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],[61, 61, 61, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 0]]]

In [56]:
# print(np.shape(WaitingQueue))
# print(np.shape(oldPaths))

#### Minizinc model for intersection management
The model uses the 'oldPaths' and 'WaitingQueue' variables that were previously available to generate 'paths' and 'NewWaitingQueue' variables. For this, the model considers all the constraints. Some of the constraints are:
- There are combinations of paths that cannot remain simultaneously open.
- Different vehicles have different priorities. Waiting cost of a single vehicle is calculated by multiplying the time it has been waiting with its priority value.
- The total waiting cost of the system needs to be minimized.
- Changing a particular signal from red to green has an additional cost.

In [57]:
%%mzn_model Intersection


int: maxQueue = 15;
set of int: AllPaths = 1..12;
set of int: Serial = 1..15;
set of int: Property = 1..2;

array[AllPaths,Property,Serial] of int: WaitingQueue;
array[AllPaths,Property,Serial] of var int: NewWaitingQueue;



%Paths array holds all the 12 paths available in a 6 lane street intersection. The variables will be turned to 0 to represent red light and 1 to represent green light.
array[AllPaths] of var 0..1: paths;

array[AllPaths] of 0..1: oldPaths;

%Cost of keeping a red light red
int:WaitingCost = 20;

%All the paths that cannot be simultaneously on
constraint paths[1]*paths[3]=0;
constraint paths[1]*paths[6]=0;
constraint paths[1]*paths[8]=0;
constraint paths[1]*paths[7]=0;
constraint paths[2]*paths[3]=0;
constraint paths[2]*paths[4]=0;
constraint paths[2]*paths[8]=0;
constraint paths[2]*paths[6]=0;
constraint paths[2]*paths[5]=0;
constraint paths[3]*paths[5]=0;
constraint paths[3]*paths[8]=0;
constraint paths[4]*paths[5]=0;
constraint paths[4]*paths[8]=0;
constraint paths[4]*paths[6]=0;
constraint paths[4]*paths[7]=0;
constraint paths[5]*paths[7]=0;
constraint paths[6]*paths[7]=0;
constraint paths[6]*paths[8]=0;

%Waiting time cannot be negative
constraint forall(i in AllPaths,k in Serial)(NewWaitingQueue[i,2,k]>=0);

%Updating the priorities
constraint 
forall(i in AllPaths,k in Serial)(
%RED LIGHT
if paths[i]==0 then
NewWaitingQueue[i,1,k]=WaitingQueue[i,1,k]
%GREEN LIGHT
elseif oldPaths[i]==1 /\ k<=11 then %4 cars exiting queue
  NewWaitingQueue[i,1,k] = WaitingQueue[i,1,k+4]
elseif oldPaths[i]==1 /\ k>11 then %4 new spaces in the queue
  NewWaitingQueue[i,1,k] = 0
elseif oldPaths[i]==0 /\ k<=13 then %2 cars exiting queue
  NewWaitingQueue[i,1,k] = WaitingQueue[i,1,k+2]
elseif oldPaths[i]==0 /\ k>13 then %2 new spaces in the queue
  NewWaitingQueue[i,1,k] = 0
else true
endif
);

%Updating the waiting time
constraint 
forall(i in AllPaths,k in Serial)(
%RED LIGHT
if paths[i]==0 /\ WaitingQueue[i,1,k]>0 then 
NewWaitingQueue[i,2,k]=(WaitingQueue[i,2,k]+WaitingCost)
%GREEN LIGHT
elseif oldPaths[i]==1 /\ k<=11 /\ WaitingQueue[i,1,k+4]>0 then %4 cars exiting queue
  NewWaitingQueue[i,2,k] = WaitingQueue[i,2,k+4]+WaitingCost
elseif oldPaths[i]==1 /\ k<=11 /\ WaitingQueue[i,1,k+4]==0 then
  NewWaitingQueue[i,2,k] = 0
elseif oldPaths[i]==1 /\ k>11 then %4 new spaces in the queue
  NewWaitingQueue[i,2,k] = 0
elseif oldPaths[i]==0 /\ k<=13 /\ WaitingQueue[i,1,k+2]>0 then %2 cars exiting queue
  NewWaitingQueue[i,2,k] = WaitingQueue[i,2,k+2]+WaitingCost
elseif oldPaths[i]==0 /\ k<=13 /\ WaitingQueue[i,1,k+2]==0 then
  NewWaitingQueue[i,2,k] = 0
elseif oldPaths[i]==0 /\ k>13 then %2 new spaces in the queue
  NewWaitingQueue[i,2,k] = 0
else true
endif

);


var int: TotalSum = sum(i in AllPaths,j in Property, k in Serial)(abs(paths[i]-1)*NewWaitingQueue[i,j,k]);

solve minimize TotalSum;


In [58]:
print("--------------xxxxxxxx----------------")
print(oldPaths)
print("--------------xxxxxxxx----------------")
print(np.array(WaitingQueue))

%minizinc Intersection -m bind
oldPaths = paths
WaitingQueue = NewWaitingQueue
print("--------------xxxxxxxx----------------")
print(oldPaths)
print("--------------xxxxxxxx----------------")
print(np.array(WaitingQueue))

%minizinc Intersection -m bind
oldPaths = paths
WaitingQueue = NewWaitingQueue
print("--------------xxxxxxxx----------------")
print(oldPaths)
print("--------------xxxxxxxx----------------")
print(np.array(WaitingQueue))

--------------xxxxxxxx----------------
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
--------------xxxxxxxx----------------
[[[20 15  5 15 15 15 15  5  5 25 20 20 10  5 25]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 5  5 15  5  5 15 15  5 25 25 10 10  5 25 10]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[15  5  5 15 10 25 25 20  5 15 20 10 20 10 15]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[25 20 10 15 15 20 20 20  5 10 20 25 20 25 20]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[20  5 20 25 10  5 20 25 25 10 15 15 15 15 20]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[25  5  5  5 15 25 20 25 20 10 15  5 20 25 15]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[20 15 15 15  5 25 20  5 10 20 20 20 25 10 20]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[25 10 15  5 15 10 10 10 10  5 10  5  5 25 15]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[15 15 10 10 20 10 20 25 25 15 10 20  5 10 15]
  [ 0  0  0  0  0  0  0  0  0  0  0 

In [59]:
%%minizinc?

